### ISSUE TITLE
Are hardcoded plugins actually hardcoded?

### ISSUE THREAD

**Issue by Ortham** [Ortham/libloadorder#81]
In some cases they seem like they could be specified by ini settings, e.g. looking at the ini files I've got in My Games subdirectories:

Skyrim SE has the following in `Skyrim.ini`:

```
[General]
sTestFile1=Dawnguard.esm
sTestFile2=HearthFires.esm
sTestFile3=Dragonborn.esm
```

Fallout 3 has the following in `FALLOUT.INI`:

```
[General]
STestFile1=Fallout3.esm
```

Fallout New Vegas has the following in `Fallout.ini`:

```
[General]
STestFile2=FalloutNV_lang.esp
STestFile1=FalloutNV.esm
```

libloadorder currently has hardcoded plugins listed for:

- Skyrim
- Skyrim SE
- Skyrim VR
- Fallout 4
- Fallout 4 VR
- Starfield

**Comment by Ortham** [comment]
- Oblivion: `Oblivion.exe` contains `sTestFile1` through to `sTestFile10`, as well as `sLocalMasterPath`, `Oblivion.esm` and `OblivionSE.esm`
- Fallout 3: `Fallout3.exe` contains `sTestFile1` through to `sTestFile10`, as well as `sLocalMasterPath`, `FALLOUT3.ESM`, `Fallout.esm` and `Data\Fallout3.esm, Data\Fallout - Misc.bsa, Data\Fallout - Sound.bsa, Data\final_master_xml.dat, Data\Shaders\shaderpackage.sdp, Data\Music\Battle\*, Data\Music\Battle\Finale\*, Data\Music\Base\*, Data\Music\Dungeon\*, Data\Music\Endgame\*, Data\Music\Explore\*, Data\Music\Public\*, Data\Music\Special\*, Data\Music\Tension\*, Data\Music\TranquilityLane\*`
- Fallout NV: `FalloutNV.exe` contains contains `sTestFile1` through to `sTestFile10`, as well as `sLocalMasterPath`, `FalloutNV.ESM`, `Fallout.esm`, `FalloutNV.esm` and `Data\FalloutNV.esm, Data\Fallout - Misc.bsa, Data\Fallout - Sound.bsa, Data\final_master_xml.dat, Data\Shaders\shaderpackage.sdp, Data\Music\Battle\*, Data\Music\Battle\Finale\*, Data\Music\Base\*, Data\Music\Dungeon\*, Data\Music\Endgame\*, Data\Music\Explore\*, Data\Music\Public\*, Data\Music\Special\*, Data\Music\Tension\*, Data\Music\TranquilityLane\*`
- Skyrim: `TESV.exe` contains `sTestFile1` through to `sTestFile10`, as well as `sLocalMasterPath`, `update.esm`, `SKYRIM.ESM` and `Skyrim.ESM`.
- Skyrim SE: `SkyrimSE.exe` contains `sTestFile1` through to `sTestFile10`, as well as `sBaseGameMasterfile`, `sLocalMasterPath`, `update.esm`, `SKYRIM.ESM`, `skyrim.esm`, `Skyrim.esm`, `Dawnguard.esm`, `HearthFires.esm`, `Dragonborn.esm`,  `Update.esm` and `Skyrim.esm, Update.esm, Dawnguard.esm, HearthFires.esm, Dragonborn.esm`
- Starfield: `SkyrimSE.exe` contains `sTestFile1` through to `sTestFile10`, as well as `sBaseGameMasterfile`, `sLocalMasterPath`, `TestData.esm`, `BlueprintShips-Starfield.esm`, `Starfield.ESM`, `Constellation.esm`, `OldMars.esm`, `Data/OldMars.esm` and `Data/Constellation.esm`

**Comment by Ortham** [comment]
Oblivion

Oblivion.exe attempts to read:

Oblivion.ini
Documents/My Games/Oblivion/Oblivion.ini

Setting an STestFile<N> variable in either one makes the game load that plugin. STestFile<N> is only used if it appears in the [General] section. The load order used is according to plugin timestamps.

---

Fallout 3

Fallout3.exe attempts to read:

Custom.ini
FALLOUT.INI
My Games/Fallout3/FALLOUT.INI
My Games/Fallout3/FalloutPrefs.ini

My Games/Fallout3/FALLOUT.INI has STestFile1=Fallout3.esm under [General], without Fallout3.esm set in the ini or plugins.txt, the game crashes on load.

My Games/Fallout3/FalloutPrefs.ini doesn't seem relevant, if I move STestFile1 to there the game crashes on load. The same is true for Custom.ini and Fallout.ini in the install folder.

---

Fallout NV

FalloutNV.exe attempts to read:

Custom.ini
FALLOUT.INI
My Games/FalloutNV/Fallout.ini
My Games/FalloutNV/FalloutPrefs.ini

My Games/FalloutNV/Fallout.ini has:

STestFile2=FalloutNV_lang.esp
STestFile1=FalloutNV.esm

My Games/FalloutNV/FalloutPrefs.ini has:

STestFile1=FalloutNV.esm

Commenting out them seems to have no effect, FalloutNV.esm is still loaded. Also it seems like all DLC plugins are loaded in timestamp order despite not being listed anywhere (tested with items from Dead Money and Honest Hearts). This needs more investigation.

**Comment by Ortham** [comment]
The results above show that the answer to the title question is yes, the hardcoded plugins are actually hardcoded.

However, it looks like Fallout NV's DLC plugins are also hardcoded, as they always load even if they're not listed anywhere (I've only verified this for a few plugins so far). However, their load order is still decided by their timestamps.

| Plugin | Always loaded? |
|-------|----------------|
| FalloutNV.esm | Yes |
| FalloutNV_lang.esp | |
| LonesomeRoad.esm | |
| OldWorldBlues.esm | |
| HonestHearts.esm | Yes |
| DeadMoney.esm | Yes |
| GunRunnersArsenal.esm | |
| CaravanPack.esm | |
| ClassicPack.esm | |
| MercenaryPack.esm | |
| TribalPack.esm | |

**Comment by sibir-ine** [comment]
Does the presence of the NAM files have anything to do with whether FNV's DLC are loaded? I vaguely remember hearing something about them being relevant.

**Comment by Ortham** [comment]
> Does the presence of the NAM files have anything to do with whether FNV's DLC are loaded? I vaguely remember hearing something about them being relevant.

Ah, yeah, that's it - if a plugin has a .nam file then it'll be activated and listed as a DLC in-game. That also explains why FalloutNV.esm is loaded, it's pulled in as the master of the DLC plugins.

I'll need to add support for treating plugins with .nam files as implicitly active for Fallout NV.

**Comment by Ortham** [comment]
Done in e0a02f0dd6ecfbdcc17ccba949f3626fb0a25715.
